namespace Glide.Core.Commands;

/// <summary>
/// Stable semantic actions. Physical input, menus, hotkeys and buttons target these names;
/// feature code must never depend on which physical control triggered the action.
/// </summary>
public enum GlideCommand
{
    None = 0,
    OpenFile,
    OpenFolder,
    RefreshFolder,
    Home,
    PreviousImage,
    NextImage,
    FirstImage,
    LastImage,
    PreviousFolder,
    NextFolder,
    ExploreParentFolder,
    FitImage,
    FitWidth,
    FitHeight,
    ActualSize,
    ToggleFitActual,
    ZoomIn,
    ZoomOut,
    RotateLeft,
    RotateRight,
    FlipHorizontal,
    FlipVertical,
    NewTab,
    CloseTab,
    RestoreClosedTab,
    DuplicateTab,
    NewWindowSameImage,
    DuplicateSessionWindow,
    NextTab,
    PreviousTab,
    SelectTab1,
    SelectTab2,
    SelectTab3,
    SelectTab4,
    SelectTab5,
    SelectTab6,
    SelectTab7,
    SelectTab8,
    SelectLastTab,
    DetachTab,
    CloseWindow,
    ToggleFullscreen,
    StartPauseSlideshow,
    StopSlideshow,
    ToggleImageInfo,
    ClearSelection,
    Settings,
    ToggleAlwaysOnTop,
    ToggleStatusSurface,
    ToggleTransparency,
    ShowContextMenu,
    BrowserBack,
    BrowserForward,
    BrowserUp,
    AddOverlay,
    SaveOverlayLayout,
    LoadOverlayLayout,
    ResetSelectedOverlayZoom,
    BringSelectedOverlayFront,
    CopyImage,
    ExportSelection,
    CopyFile,
    CopyFileName,
    CopyFolderPath,
    CopyFullPath,
    RenameFile,
    DeleteFile,
    OpenContainingFolder,
    Print,
    ExternalProgram1,
    ExternalProgram2,
    ExternalProgram3
}
