; GENERATED FILE - do not edit directly.
; Source of truth: ..\image_formats.h (GlideFormats::kImageExtensions)
; Generated by installer\generate_associations.ps1 before every installer build.
Root: HKLM64; Subkey: "Software\Classes\Applications\Glide.exe\SupportedTypes"; ValueType: string; ValueName: ".jpg"; ValueData: ""; Flags: uninsdeletevalue
Root: HKLM64; Subkey: "Software\Glide Image Viewer\Capabilities\FileAssociations"; ValueType: string; ValueName: ".jpg"; ValueData: "Glide.Image"; Flags: uninsdeletevalue
Root: HKLM64; Subkey: "Software\Classes\Applications\Glide.exe\SupportedTypes"; ValueType: string; ValueName: ".jpeg"; ValueData: ""; Flags: uninsdeletevalue
Root: HKLM64; Subkey: "Software\Glide Image Viewer\Capabilities\FileAssociations"; ValueType: string; ValueName: ".jpeg"; ValueData: "Glide.Image"; Flags: uninsdeletevalue
Root: HKLM64; Subkey: "Software\Classes\Applications\Glide.exe\SupportedTypes"; ValueType: string; ValueName: ".jpe"; ValueData: ""; Flags: uninsdeletevalue
Root: HKLM64; Subkey: "Software\Glide Image Viewer\Capabilities\FileAssociations"; ValueType: string; ValueName: ".jpe"; ValueData: "Glide.Image"; Flags: uninsdeletevalue
Root: HKLM64; Subkey: "Software\Classes\Applications\Glide.exe\SupportedTypes"; ValueType: string; ValueName: ".jfif"; ValueData: ""; Flags: uninsdeletevalue
Root: HKLM64; Subkey: "Software\Glide Image Viewer\Capabilities\FileAssociations"; ValueType: string; ValueName: ".jfif"; ValueData: "Glide.Image"; Flags: uninsdeletevalue
Root: HKLM64; Subkey: "Software\Classes\Applications\Glide.exe\SupportedTypes"; ValueType: string; ValueName: ".jif"; ValueData: ""; Flags: uninsdeletevalue
Root: HKLM64; Subkey: "Software\Glide Image Viewer\Capabilities\FileAssociations"; ValueType: string; ValueName: ".jif"; ValueData: "Glide.Image"; Flags: uninsdeletevalue
Root: HKLM64; Subkey: "Software\Classes\Applications\Glide.exe\SupportedTypes"; ValueType: string; ValueName: ".jfi"; ValueData: ""; Flags: uninsdeletevalue
Root: HKLM64; Subkey: "Software\Glide Image Viewer\Capabilities\FileAssociations"; ValueType: string; ValueName: ".jfi"; ValueData: "Glide.Image"; Flags: uninsdeletevalue
Root: HKLM64; Subkey: "Software\Classes\Applications\Glide.exe\SupportedTypes"; ValueType: string; ValueName: ".png"; ValueData: ""; Flags: uninsdeletevalue
Root: HKLM64; Subkey: "Software\Glide Image Viewer\Capabilities\FileAssociations"; ValueType: string; ValueName: ".png"; ValueData: "Glide.Image"; Flags: uninsdeletevalue
Root: HKLM64; Subkey: "Software\Classes\Applications\Glide.exe\SupportedTypes"; ValueType: string; ValueName: ".apng"; ValueData: ""; Flags: uninsdeletevalue
Root: HKLM64; Subkey: "Software\Glide Image Viewer\Capabilities\FileAssociations"; ValueType: string; ValueName: ".apng"; ValueData: "Glide.Image"; Flags: uninsdeletevalue
Root: HKLM64; Subkey: "Software\Classes\Applications\Glide.exe\SupportedTypes"; ValueType: string; ValueName: ".bmp"; ValueData: ""; Flags: uninsdeletevalue
Root: HKLM64; Subkey: "Software\Glide Image Viewer\Capabilities\FileAssociations"; ValueType: string; ValueName: ".bmp"; ValueData: "Glide.Image"; Flags: uninsdeletevalue
Root: HKLM64; Subkey: "Software\Classes\Applications\Glide.exe\SupportedTypes"; ValueType: string; ValueName: ".dib"; ValueData: ""; Flags: uninsdeletevalue
Root: HKLM64; Subkey: "Software\Glide Image Viewer\Capabilities\FileAssociations"; ValueType: string; ValueName: ".dib"; ValueData: "Glide.Image"; Flags: uninsdeletevalue
Root: HKLM64; Subkey: "Software\Classes\Applications\Glide.exe\SupportedTypes"; ValueType: string; ValueName: ".rle"; ValueData: ""; Flags: uninsdeletevalue
Root: HKLM64; Subkey: "Software\Glide Image Viewer\Capabilities\FileAssociations"; ValueType: string; ValueName: ".rle"; ValueData: "Glide.Image"; Flags: uninsdeletevalue
Root: HKLM64; Subkey: "Software\Classes\Applications\Glide.exe\SupportedTypes"; ValueType: string; ValueName: ".tif"; ValueData: ""; Flags: uninsdeletevalue
Root: HKLM64; Subkey: "Software\Glide Image Viewer\Capabilities\FileAssociations"; ValueType: string; ValueName: ".tif"; ValueData: "Glide.Image"; Flags: uninsdeletevalue
Root: HKLM64; Subkey: "Software\Classes\Applications\Glide.exe\SupportedTypes"; ValueType: string; ValueName: ".tiff"; ValueData: ""; Flags: uninsdeletevalue
Root: HKLM64; Subkey: "Software\Glide Image Viewer\Capabilities\FileAssociations"; ValueType: string; ValueName: ".tiff"; ValueData: "Glide.Image"; Flags: uninsdeletevalue
Root: HKLM64; Subkey: "Software\Classes\Applications\Glide.exe\SupportedTypes"; ValueType: string; ValueName: ".btf"; ValueData: ""; Flags: uninsdeletevalue
Root: HKLM64; Subkey: "Software\Glide Image Viewer\Capabilities\FileAssociations"; ValueType: string; ValueName: ".btf"; ValueData: "Glide.Image"; Flags: uninsdeletevalue
Root: HKLM64; Subkey: "Software\Classes\Applications\Glide.exe\SupportedTypes"; ValueType: string; ValueName: ".gif"; ValueData: ""; Flags: uninsdeletevalue
Root: HKLM64; Subkey: "Software\Glide Image Viewer\Capabilities\FileAssociations"; ValueType: string; ValueName: ".gif"; ValueData: "Glide.Image"; Flags: uninsdeletevalue
Root: HKLM64; Subkey: "Software\Classes\Applications\Glide.exe\SupportedTypes"; ValueType: string; ValueName: ".ico"; ValueData: ""; Flags: uninsdeletevalue
Root: HKLM64; Subkey: "Software\Glide Image Viewer\Capabilities\FileAssociations"; ValueType: string; ValueName: ".ico"; ValueData: "Glide.Image"; Flags: uninsdeletevalue
Root: HKLM64; Subkey: "Software\Classes\Applications\Glide.exe\SupportedTypes"; ValueType: string; ValueName: ".cur"; ValueData: ""; Flags: uninsdeletevalue
Root: HKLM64; Subkey: "Software\Glide Image Viewer\Capabilities\FileAssociations"; ValueType: string; ValueName: ".cur"; ValueData: "Glide.Image"; Flags: uninsdeletevalue
Root: HKLM64; Subkey: "Software\Classes\Applications\Glide.exe\SupportedTypes"; ValueType: string; ValueName: ".webp"; ValueData: ""; Flags: uninsdeletevalue
Root: HKLM64; Subkey: "Software\Glide Image Viewer\Capabilities\FileAssociations"; ValueType: string; ValueName: ".webp"; ValueData: "Glide.Image"; Flags: uninsdeletevalue
Root: HKLM64; Subkey: "Software\Classes\Applications\Glide.exe\SupportedTypes"; ValueType: string; ValueName: ".heic"; ValueData: ""; Flags: uninsdeletevalue
Root: HKLM64; Subkey: "Software\Glide Image Viewer\Capabilities\FileAssociations"; ValueType: string; ValueName: ".heic"; ValueData: "Glide.Image"; Flags: uninsdeletevalue
Root: HKLM64; Subkey: "Software\Classes\Applications\Glide.exe\SupportedTypes"; ValueType: string; ValueName: ".heif"; ValueData: ""; Flags: uninsdeletevalue
Root: HKLM64; Subkey: "Software\Glide Image Viewer\Capabilities\FileAssociations"; ValueType: string; ValueName: ".heif"; ValueData: "Glide.Image"; Flags: uninsdeletevalue
Root: HKLM64; Subkey: "Software\Classes\Applications\Glide.exe\SupportedTypes"; ValueType: string; ValueName: ".heics"; ValueData: ""; Flags: uninsdeletevalue
Root: HKLM64; Subkey: "Software\Glide Image Viewer\Capabilities\FileAssociations"; ValueType: string; ValueName: ".heics"; ValueData: "Glide.Image"; Flags: uninsdeletevalue
Root: HKLM64; Subkey: "Software\Classes\Applications\Glide.exe\SupportedTypes"; ValueType: string; ValueName: ".heifs"; ValueData: ""; Flags: uninsdeletevalue
Root: HKLM64; Subkey: "Software\Glide Image Viewer\Capabilities\FileAssociations"; ValueType: string; ValueName: ".heifs"; ValueData: "Glide.Image"; Flags: uninsdeletevalue
Root: HKLM64; Subkey: "Software\Classes\Applications\Glide.exe\SupportedTypes"; ValueType: string; ValueName: ".hif"; ValueData: ""; Flags: uninsdeletevalue
Root: HKLM64; Subkey: "Software\Glide Image Viewer\Capabilities\FileAssociations"; ValueType: string; ValueName: ".hif"; ValueData: "Glide.Image"; Flags: uninsdeletevalue
Root: HKLM64; Subkey: "Software\Classes\Applications\Glide.exe\SupportedTypes"; ValueType: string; ValueName: ".avif"; ValueData: ""; Flags: uninsdeletevalue
Root: HKLM64; Subkey: "Software\Glide Image Viewer\Capabilities\FileAssociations"; ValueType: string; ValueName: ".avif"; ValueData: "Glide.Image"; Flags: uninsdeletevalue
Root: HKLM64; Subkey: "Software\Classes\Applications\Glide.exe\SupportedTypes"; ValueType: string; ValueName: ".avifs"; ValueData: ""; Flags: uninsdeletevalue
Root: HKLM64; Subkey: "Software\Glide Image Viewer\Capabilities\FileAssociations"; ValueType: string; ValueName: ".avifs"; ValueData: "Glide.Image"; Flags: uninsdeletevalue
Root: HKLM64; Subkey: "Software\Classes\Applications\Glide.exe\SupportedTypes"; ValueType: string; ValueName: ".jxr"; ValueData: ""; Flags: uninsdeletevalue
Root: HKLM64; Subkey: "Software\Glide Image Viewer\Capabilities\FileAssociations"; ValueType: string; ValueName: ".jxr"; ValueData: "Glide.Image"; Flags: uninsdeletevalue
Root: HKLM64; Subkey: "Software\Classes\Applications\Glide.exe\SupportedTypes"; ValueType: string; ValueName: ".wdp"; ValueData: ""; Flags: uninsdeletevalue
Root: HKLM64; Subkey: "Software\Glide Image Viewer\Capabilities\FileAssociations"; ValueType: string; ValueName: ".wdp"; ValueData: "Glide.Image"; Flags: uninsdeletevalue
Root: HKLM64; Subkey: "Software\Classes\Applications\Glide.exe\SupportedTypes"; ValueType: string; ValueName: ".hdp"; ValueData: ""; Flags: uninsdeletevalue
Root: HKLM64; Subkey: "Software\Glide Image Viewer\Capabilities\FileAssociations"; ValueType: string; ValueName: ".hdp"; ValueData: "Glide.Image"; Flags: uninsdeletevalue
Root: HKLM64; Subkey: "Software\Classes\Applications\Glide.exe\SupportedTypes"; ValueType: string; ValueName: ".jp2"; ValueData: ""; Flags: uninsdeletevalue
Root: HKLM64; Subkey: "Software\Glide Image Viewer\Capabilities\FileAssociations"; ValueType: string; ValueName: ".jp2"; ValueData: "Glide.Image"; Flags: uninsdeletevalue
Root: HKLM64; Subkey: "Software\Classes\Applications\Glide.exe\SupportedTypes"; ValueType: string; ValueName: ".j2k"; ValueData: ""; Flags: uninsdeletevalue
Root: HKLM64; Subkey: "Software\Glide Image Viewer\Capabilities\FileAssociations"; ValueType: string; ValueName: ".j2k"; ValueData: "Glide.Image"; Flags: uninsdeletevalue
Root: HKLM64; Subkey: "Software\Classes\Applications\Glide.exe\SupportedTypes"; ValueType: string; ValueName: ".j2c"; ValueData: ""; Flags: uninsdeletevalue
Root: HKLM64; Subkey: "Software\Glide Image Viewer\Capabilities\FileAssociations"; ValueType: string; ValueName: ".j2c"; ValueData: "Glide.Image"; Flags: uninsdeletevalue
Root: HKLM64; Subkey: "Software\Classes\Applications\Glide.exe\SupportedTypes"; ValueType: string; ValueName: ".jpc"; ValueData: ""; Flags: uninsdeletevalue
Root: HKLM64; Subkey: "Software\Glide Image Viewer\Capabilities\FileAssociations"; ValueType: string; ValueName: ".jpc"; ValueData: "Glide.Image"; Flags: uninsdeletevalue
Root: HKLM64; Subkey: "Software\Classes\Applications\Glide.exe\SupportedTypes"; ValueType: string; ValueName: ".jpx"; ValueData: ""; Flags: uninsdeletevalue
Root: HKLM64; Subkey: "Software\Glide Image Viewer\Capabilities\FileAssociations"; ValueType: string; ValueName: ".jpx"; ValueData: "Glide.Image"; Flags: uninsdeletevalue
Root: HKLM64; Subkey: "Software\Classes\Applications\Glide.exe\SupportedTypes"; ValueType: string; ValueName: ".jpf"; ValueData: ""; Flags: uninsdeletevalue
Root: HKLM64; Subkey: "Software\Glide Image Viewer\Capabilities\FileAssociations"; ValueType: string; ValueName: ".jpf"; ValueData: "Glide.Image"; Flags: uninsdeletevalue
Root: HKLM64; Subkey: "Software\Classes\Applications\Glide.exe\SupportedTypes"; ValueType: string; ValueName: ".jxl"; ValueData: ""; Flags: uninsdeletevalue
Root: HKLM64; Subkey: "Software\Glide Image Viewer\Capabilities\FileAssociations"; ValueType: string; ValueName: ".jxl"; ValueData: "Glide.Image"; Flags: uninsdeletevalue
Root: HKLM64; Subkey: "Software\Classes\Applications\Glide.exe\SupportedTypes"; ValueType: string; ValueName: ".psd"; ValueData: ""; Flags: uninsdeletevalue
Root: HKLM64; Subkey: "Software\Glide Image Viewer\Capabilities\FileAssociations"; ValueType: string; ValueName: ".psd"; ValueData: "Glide.Image"; Flags: uninsdeletevalue
Root: HKLM64; Subkey: "Software\Classes\Applications\Glide.exe\SupportedTypes"; ValueType: string; ValueName: ".tga"; ValueData: ""; Flags: uninsdeletevalue
Root: HKLM64; Subkey: "Software\Glide Image Viewer\Capabilities\FileAssociations"; ValueType: string; ValueName: ".tga"; ValueData: "Glide.Image"; Flags: uninsdeletevalue
Root: HKLM64; Subkey: "Software\Classes\Applications\Glide.exe\SupportedTypes"; ValueType: string; ValueName: ".targa"; ValueData: ""; Flags: uninsdeletevalue
Root: HKLM64; Subkey: "Software\Glide Image Viewer\Capabilities\FileAssociations"; ValueType: string; ValueName: ".targa"; ValueData: "Glide.Image"; Flags: uninsdeletevalue
Root: HKLM64; Subkey: "Software\Classes\Applications\Glide.exe\SupportedTypes"; ValueType: string; ValueName: ".icb"; ValueData: ""; Flags: uninsdeletevalue
Root: HKLM64; Subkey: "Software\Glide Image Viewer\Capabilities\FileAssociations"; ValueType: string; ValueName: ".icb"; ValueData: "Glide.Image"; Flags: uninsdeletevalue
Root: HKLM64; Subkey: "Software\Classes\Applications\Glide.exe\SupportedTypes"; ValueType: string; ValueName: ".vda"; ValueData: ""; Flags: uninsdeletevalue
Root: HKLM64; Subkey: "Software\Glide Image Viewer\Capabilities\FileAssociations"; ValueType: string; ValueName: ".vda"; ValueData: "Glide.Image"; Flags: uninsdeletevalue
Root: HKLM64; Subkey: "Software\Classes\Applications\Glide.exe\SupportedTypes"; ValueType: string; ValueName: ".vst"; ValueData: ""; Flags: uninsdeletevalue
Root: HKLM64; Subkey: "Software\Glide Image Viewer\Capabilities\FileAssociations"; ValueType: string; ValueName: ".vst"; ValueData: "Glide.Image"; Flags: uninsdeletevalue
Root: HKLM64; Subkey: "Software\Classes\Applications\Glide.exe\SupportedTypes"; ValueType: string; ValueName: ".pnm"; ValueData: ""; Flags: uninsdeletevalue
Root: HKLM64; Subkey: "Software\Glide Image Viewer\Capabilities\FileAssociations"; ValueType: string; ValueName: ".pnm"; ValueData: "Glide.Image"; Flags: uninsdeletevalue
Root: HKLM64; Subkey: "Software\Classes\Applications\Glide.exe\SupportedTypes"; ValueType: string; ValueName: ".ppm"; ValueData: ""; Flags: uninsdeletevalue
Root: HKLM64; Subkey: "Software\Glide Image Viewer\Capabilities\FileAssociations"; ValueType: string; ValueName: ".ppm"; ValueData: "Glide.Image"; Flags: uninsdeletevalue
Root: HKLM64; Subkey: "Software\Classes\Applications\Glide.exe\SupportedTypes"; ValueType: string; ValueName: ".pgm"; ValueData: ""; Flags: uninsdeletevalue
Root: HKLM64; Subkey: "Software\Glide Image Viewer\Capabilities\FileAssociations"; ValueType: string; ValueName: ".pgm"; ValueData: "Glide.Image"; Flags: uninsdeletevalue
Root: HKLM64; Subkey: "Software\Classes\Applications\Glide.exe\SupportedTypes"; ValueType: string; ValueName: ".pbm"; ValueData: ""; Flags: uninsdeletevalue
Root: HKLM64; Subkey: "Software\Glide Image Viewer\Capabilities\FileAssociations"; ValueType: string; ValueName: ".pbm"; ValueData: "Glide.Image"; Flags: uninsdeletevalue
Root: HKLM64; Subkey: "Software\Classes\Applications\Glide.exe\SupportedTypes"; ValueType: string; ValueName: ".pam"; ValueData: ""; Flags: uninsdeletevalue
Root: HKLM64; Subkey: "Software\Glide Image Viewer\Capabilities\FileAssociations"; ValueType: string; ValueName: ".pam"; ValueData: "Glide.Image"; Flags: uninsdeletevalue
Root: HKLM64; Subkey: "Software\Classes\Applications\Glide.exe\SupportedTypes"; ValueType: string; ValueName: ".pcx"; ValueData: ""; Flags: uninsdeletevalue
Root: HKLM64; Subkey: "Software\Glide Image Viewer\Capabilities\FileAssociations"; ValueType: string; ValueName: ".pcx"; ValueData: "Glide.Image"; Flags: uninsdeletevalue
Root: HKLM64; Subkey: "Software\Classes\Applications\Glide.exe\SupportedTypes"; ValueType: string; ValueName: ".qoi"; ValueData: ""; Flags: uninsdeletevalue
Root: HKLM64; Subkey: "Software\Glide Image Viewer\Capabilities\FileAssociations"; ValueType: string; ValueName: ".qoi"; ValueData: "Glide.Image"; Flags: uninsdeletevalue
Root: HKLM64; Subkey: "Software\Classes\Applications\Glide.exe\SupportedTypes"; ValueType: string; ValueName: ".hdr"; ValueData: ""; Flags: uninsdeletevalue
Root: HKLM64; Subkey: "Software\Glide Image Viewer\Capabilities\FileAssociations"; ValueType: string; ValueName: ".hdr"; ValueData: "Glide.Image"; Flags: uninsdeletevalue
Root: HKLM64; Subkey: "Software\Classes\Applications\Glide.exe\SupportedTypes"; ValueType: string; ValueName: ".rgbe"; ValueData: ""; Flags: uninsdeletevalue
Root: HKLM64; Subkey: "Software\Glide Image Viewer\Capabilities\FileAssociations"; ValueType: string; ValueName: ".rgbe"; ValueData: "Glide.Image"; Flags: uninsdeletevalue
Root: HKLM64; Subkey: "Software\Classes\Applications\Glide.exe\SupportedTypes"; ValueType: string; ValueName: ".xyze"; ValueData: ""; Flags: uninsdeletevalue
Root: HKLM64; Subkey: "Software\Glide Image Viewer\Capabilities\FileAssociations"; ValueType: string; ValueName: ".xyze"; ValueData: "Glide.Image"; Flags: uninsdeletevalue
Root: HKLM64; Subkey: "Software\Classes\Applications\Glide.exe\SupportedTypes"; ValueType: string; ValueName: ".exr"; ValueData: ""; Flags: uninsdeletevalue
Root: HKLM64; Subkey: "Software\Glide Image Viewer\Capabilities\FileAssociations"; ValueType: string; ValueName: ".exr"; ValueData: "Glide.Image"; Flags: uninsdeletevalue
Root: HKLM64; Subkey: "Software\Classes\Applications\Glide.exe\SupportedTypes"; ValueType: string; ValueName: ".dds"; ValueData: ""; Flags: uninsdeletevalue
Root: HKLM64; Subkey: "Software\Glide Image Viewer\Capabilities\FileAssociations"; ValueType: string; ValueName: ".dds"; ValueData: "Glide.Image"; Flags: uninsdeletevalue
Root: HKLM64; Subkey: "Software\Classes\Applications\Glide.exe\SupportedTypes"; ValueType: string; ValueName: ".ff"; ValueData: ""; Flags: uninsdeletevalue
Root: HKLM64; Subkey: "Software\Glide Image Viewer\Capabilities\FileAssociations"; ValueType: string; ValueName: ".ff"; ValueData: "Glide.Image"; Flags: uninsdeletevalue
Root: HKLM64; Subkey: "Software\Classes\Applications\Glide.exe\SupportedTypes"; ValueType: string; ValueName: ".dng"; ValueData: ""; Flags: uninsdeletevalue
Root: HKLM64; Subkey: "Software\Glide Image Viewer\Capabilities\FileAssociations"; ValueType: string; ValueName: ".dng"; ValueData: "Glide.Image"; Flags: uninsdeletevalue
Root: HKLM64; Subkey: "Software\Classes\Applications\Glide.exe\SupportedTypes"; ValueType: string; ValueName: ".cr2"; ValueData: ""; Flags: uninsdeletevalue
Root: HKLM64; Subkey: "Software\Glide Image Viewer\Capabilities\FileAssociations"; ValueType: string; ValueName: ".cr2"; ValueData: "Glide.Image"; Flags: uninsdeletevalue
Root: HKLM64; Subkey: "Software\Classes\Applications\Glide.exe\SupportedTypes"; ValueType: string; ValueName: ".cr3"; ValueData: ""; Flags: uninsdeletevalue
Root: HKLM64; Subkey: "Software\Glide Image Viewer\Capabilities\FileAssociations"; ValueType: string; ValueName: ".cr3"; ValueData: "Glide.Image"; Flags: uninsdeletevalue
Root: HKLM64; Subkey: "Software\Classes\Applications\Glide.exe\SupportedTypes"; ValueType: string; ValueName: ".crw"; ValueData: ""; Flags: uninsdeletevalue
Root: HKLM64; Subkey: "Software\Glide Image Viewer\Capabilities\FileAssociations"; ValueType: string; ValueName: ".crw"; ValueData: "Glide.Image"; Flags: uninsdeletevalue
Root: HKLM64; Subkey: "Software\Classes\Applications\Glide.exe\SupportedTypes"; ValueType: string; ValueName: ".nef"; ValueData: ""; Flags: uninsdeletevalue
Root: HKLM64; Subkey: "Software\Glide Image Viewer\Capabilities\FileAssociations"; ValueType: string; ValueName: ".nef"; ValueData: "Glide.Image"; Flags: uninsdeletevalue
Root: HKLM64; Subkey: "Software\Classes\Applications\Glide.exe\SupportedTypes"; ValueType: string; ValueName: ".nrw"; ValueData: ""; Flags: uninsdeletevalue
Root: HKLM64; Subkey: "Software\Glide Image Viewer\Capabilities\FileAssociations"; ValueType: string; ValueName: ".nrw"; ValueData: "Glide.Image"; Flags: uninsdeletevalue
Root: HKLM64; Subkey: "Software\Classes\Applications\Glide.exe\SupportedTypes"; ValueType: string; ValueName: ".arw"; ValueData: ""; Flags: uninsdeletevalue
Root: HKLM64; Subkey: "Software\Glide Image Viewer\Capabilities\FileAssociations"; ValueType: string; ValueName: ".arw"; ValueData: "Glide.Image"; Flags: uninsdeletevalue
Root: HKLM64; Subkey: "Software\Classes\Applications\Glide.exe\SupportedTypes"; ValueType: string; ValueName: ".srf"; ValueData: ""; Flags: uninsdeletevalue
Root: HKLM64; Subkey: "Software\Glide Image Viewer\Capabilities\FileAssociations"; ValueType: string; ValueName: ".srf"; ValueData: "Glide.Image"; Flags: uninsdeletevalue
Root: HKLM64; Subkey: "Software\Classes\Applications\Glide.exe\SupportedTypes"; ValueType: string; ValueName: ".sr2"; ValueData: ""; Flags: uninsdeletevalue
Root: HKLM64; Subkey: "Software\Glide Image Viewer\Capabilities\FileAssociations"; ValueType: string; ValueName: ".sr2"; ValueData: "Glide.Image"; Flags: uninsdeletevalue
Root: HKLM64; Subkey: "Software\Classes\Applications\Glide.exe\SupportedTypes"; ValueType: string; ValueName: ".raf"; ValueData: ""; Flags: uninsdeletevalue
Root: HKLM64; Subkey: "Software\Glide Image Viewer\Capabilities\FileAssociations"; ValueType: string; ValueName: ".raf"; ValueData: "Glide.Image"; Flags: uninsdeletevalue
Root: HKLM64; Subkey: "Software\Classes\Applications\Glide.exe\SupportedTypes"; ValueType: string; ValueName: ".orf"; ValueData: ""; Flags: uninsdeletevalue
Root: HKLM64; Subkey: "Software\Glide Image Viewer\Capabilities\FileAssociations"; ValueType: string; ValueName: ".orf"; ValueData: "Glide.Image"; Flags: uninsdeletevalue
Root: HKLM64; Subkey: "Software\Classes\Applications\Glide.exe\SupportedTypes"; ValueType: string; ValueName: ".ori"; ValueData: ""; Flags: uninsdeletevalue
Root: HKLM64; Subkey: "Software\Glide Image Viewer\Capabilities\FileAssociations"; ValueType: string; ValueName: ".ori"; ValueData: "Glide.Image"; Flags: uninsdeletevalue
Root: HKLM64; Subkey: "Software\Classes\Applications\Glide.exe\SupportedTypes"; ValueType: string; ValueName: ".rw2"; ValueData: ""; Flags: uninsdeletevalue
Root: HKLM64; Subkey: "Software\Glide Image Viewer\Capabilities\FileAssociations"; ValueType: string; ValueName: ".rw2"; ValueData: "Glide.Image"; Flags: uninsdeletevalue
Root: HKLM64; Subkey: "Software\Classes\Applications\Glide.exe\SupportedTypes"; ValueType: string; ValueName: ".rwl"; ValueData: ""; Flags: uninsdeletevalue
Root: HKLM64; Subkey: "Software\Glide Image Viewer\Capabilities\FileAssociations"; ValueType: string; ValueName: ".rwl"; ValueData: "Glide.Image"; Flags: uninsdeletevalue
Root: HKLM64; Subkey: "Software\Classes\Applications\Glide.exe\SupportedTypes"; ValueType: string; ValueName: ".pef"; ValueData: ""; Flags: uninsdeletevalue
Root: HKLM64; Subkey: "Software\Glide Image Viewer\Capabilities\FileAssociations"; ValueType: string; ValueName: ".pef"; ValueData: "Glide.Image"; Flags: uninsdeletevalue
Root: HKLM64; Subkey: "Software\Classes\Applications\Glide.exe\SupportedTypes"; ValueType: string; ValueName: ".ptx"; ValueData: ""; Flags: uninsdeletevalue
Root: HKLM64; Subkey: "Software\Glide Image Viewer\Capabilities\FileAssociations"; ValueType: string; ValueName: ".ptx"; ValueData: "Glide.Image"; Flags: uninsdeletevalue
Root: HKLM64; Subkey: "Software\Classes\Applications\Glide.exe\SupportedTypes"; ValueType: string; ValueName: ".3fr"; ValueData: ""; Flags: uninsdeletevalue
Root: HKLM64; Subkey: "Software\Glide Image Viewer\Capabilities\FileAssociations"; ValueType: string; ValueName: ".3fr"; ValueData: "Glide.Image"; Flags: uninsdeletevalue
Root: HKLM64; Subkey: "Software\Classes\Applications\Glide.exe\SupportedTypes"; ValueType: string; ValueName: ".fff"; ValueData: ""; Flags: uninsdeletevalue
Root: HKLM64; Subkey: "Software\Glide Image Viewer\Capabilities\FileAssociations"; ValueType: string; ValueName: ".fff"; ValueData: "Glide.Image"; Flags: uninsdeletevalue
Root: HKLM64; Subkey: "Software\Classes\Applications\Glide.exe\SupportedTypes"; ValueType: string; ValueName: ".iiq"; ValueData: ""; Flags: uninsdeletevalue
Root: HKLM64; Subkey: "Software\Glide Image Viewer\Capabilities\FileAssociations"; ValueType: string; ValueName: ".iiq"; ValueData: "Glide.Image"; Flags: uninsdeletevalue
Root: HKLM64; Subkey: "Software\Classes\Applications\Glide.exe\SupportedTypes"; ValueType: string; ValueName: ".cap"; ValueData: ""; Flags: uninsdeletevalue
Root: HKLM64; Subkey: "Software\Glide Image Viewer\Capabilities\FileAssociations"; ValueType: string; ValueName: ".cap"; ValueData: "Glide.Image"; Flags: uninsdeletevalue
Root: HKLM64; Subkey: "Software\Classes\Applications\Glide.exe\SupportedTypes"; ValueType: string; ValueName: ".eip"; ValueData: ""; Flags: uninsdeletevalue
Root: HKLM64; Subkey: "Software\Glide Image Viewer\Capabilities\FileAssociations"; ValueType: string; ValueName: ".eip"; ValueData: "Glide.Image"; Flags: uninsdeletevalue
Root: HKLM64; Subkey: "Software\Classes\Applications\Glide.exe\SupportedTypes"; ValueType: string; ValueName: ".mef"; ValueData: ""; Flags: uninsdeletevalue
Root: HKLM64; Subkey: "Software\Glide Image Viewer\Capabilities\FileAssociations"; ValueType: string; ValueName: ".mef"; ValueData: "Glide.Image"; Flags: uninsdeletevalue
Root: HKLM64; Subkey: "Software\Classes\Applications\Glide.exe\SupportedTypes"; ValueType: string; ValueName: ".mos"; ValueData: ""; Flags: uninsdeletevalue
Root: HKLM64; Subkey: "Software\Glide Image Viewer\Capabilities\FileAssociations"; ValueType: string; ValueName: ".mos"; ValueData: "Glide.Image"; Flags: uninsdeletevalue
Root: HKLM64; Subkey: "Software\Classes\Applications\Glide.exe\SupportedTypes"; ValueType: string; ValueName: ".mrw"; ValueData: ""; Flags: uninsdeletevalue
Root: HKLM64; Subkey: "Software\Glide Image Viewer\Capabilities\FileAssociations"; ValueType: string; ValueName: ".mrw"; ValueData: "Glide.Image"; Flags: uninsdeletevalue
Root: HKLM64; Subkey: "Software\Classes\Applications\Glide.exe\SupportedTypes"; ValueType: string; ValueName: ".x3f"; ValueData: ""; Flags: uninsdeletevalue
Root: HKLM64; Subkey: "Software\Glide Image Viewer\Capabilities\FileAssociations"; ValueType: string; ValueName: ".x3f"; ValueData: "Glide.Image"; Flags: uninsdeletevalue
Root: HKLM64; Subkey: "Software\Classes\Applications\Glide.exe\SupportedTypes"; ValueType: string; ValueName: ".erf"; ValueData: ""; Flags: uninsdeletevalue
Root: HKLM64; Subkey: "Software\Glide Image Viewer\Capabilities\FileAssociations"; ValueType: string; ValueName: ".erf"; ValueData: "Glide.Image"; Flags: uninsdeletevalue
Root: HKLM64; Subkey: "Software\Classes\Applications\Glide.exe\SupportedTypes"; ValueType: string; ValueName: ".kdc"; ValueData: ""; Flags: uninsdeletevalue
Root: HKLM64; Subkey: "Software\Glide Image Viewer\Capabilities\FileAssociations"; ValueType: string; ValueName: ".kdc"; ValueData: "Glide.Image"; Flags: uninsdeletevalue
Root: HKLM64; Subkey: "Software\Classes\Applications\Glide.exe\SupportedTypes"; ValueType: string; ValueName: ".dcr"; ValueData: ""; Flags: uninsdeletevalue
Root: HKLM64; Subkey: "Software\Glide Image Viewer\Capabilities\FileAssociations"; ValueType: string; ValueName: ".dcr"; ValueData: "Glide.Image"; Flags: uninsdeletevalue
Root: HKLM64; Subkey: "Software\Classes\Applications\Glide.exe\SupportedTypes"; ValueType: string; ValueName: ".k25"; ValueData: ""; Flags: uninsdeletevalue
Root: HKLM64; Subkey: "Software\Glide Image Viewer\Capabilities\FileAssociations"; ValueType: string; ValueName: ".k25"; ValueData: "Glide.Image"; Flags: uninsdeletevalue
Root: HKLM64; Subkey: "Software\Classes\Applications\Glide.exe\SupportedTypes"; ValueType: string; ValueName: ".bay"; ValueData: ""; Flags: uninsdeletevalue
Root: HKLM64; Subkey: "Software\Glide Image Viewer\Capabilities\FileAssociations"; ValueType: string; ValueName: ".bay"; ValueData: "Glide.Image"; Flags: uninsdeletevalue
Root: HKLM64; Subkey: "Software\Classes\Applications\Glide.exe\SupportedTypes"; ValueType: string; ValueName: ".srw"; ValueData: ""; Flags: uninsdeletevalue
Root: HKLM64; Subkey: "Software\Glide Image Viewer\Capabilities\FileAssociations"; ValueType: string; ValueName: ".srw"; ValueData: "Glide.Image"; Flags: uninsdeletevalue
Root: HKLM64; Subkey: "Software\Classes\Applications\Glide.exe\SupportedTypes"; ValueType: string; ValueName: ".rwz"; ValueData: ""; Flags: uninsdeletevalue
Root: HKLM64; Subkey: "Software\Glide Image Viewer\Capabilities\FileAssociations"; ValueType: string; ValueName: ".rwz"; ValueData: "Glide.Image"; Flags: uninsdeletevalue
Root: HKLM64; Subkey: "Software\Classes\Applications\Glide.exe\SupportedTypes"; ValueType: string; ValueName: ".gpr"; ValueData: ""; Flags: uninsdeletevalue
Root: HKLM64; Subkey: "Software\Glide Image Viewer\Capabilities\FileAssociations"; ValueType: string; ValueName: ".gpr"; ValueData: "Glide.Image"; Flags: uninsdeletevalue
Root: HKLM64; Subkey: "Software\Classes\Applications\Glide.exe\SupportedTypes"; ValueType: string; ValueName: ".mdc"; ValueData: ""; Flags: uninsdeletevalue
Root: HKLM64; Subkey: "Software\Glide Image Viewer\Capabilities\FileAssociations"; ValueType: string; ValueName: ".mdc"; ValueData: "Glide.Image"; Flags: uninsdeletevalue
Root: HKLM64; Subkey: "Software\Classes\Applications\Glide.exe\SupportedTypes"; ValueType: string; ValueName: ".raw"; ValueData: ""; Flags: uninsdeletevalue
Root: HKLM64; Subkey: "Software\Glide Image Viewer\Capabilities\FileAssociations"; ValueType: string; ValueName: ".raw"; ValueData: "Glide.Image"; Flags: uninsdeletevalue
