param(
    [Parameter(Mandatory=$true)][string]$HeaderPath,
    [Parameter(Mandatory=$true)][string]$OutputPath
)

$ErrorActionPreference = 'Stop'
$text = Get-Content -LiteralPath $HeaderPath -Raw -Encoding UTF8
$match = [regex]::Match($text, 'kImageExtensions(?:\s*\[\s*\])?\s*=\s*\{(?<body>.*?)\};', [System.Text.RegularExpressions.RegexOptions]::Singleline)
if (-not $match.Success) { throw 'Could not locate GlideFormats::kImageExtensions in image_formats.h.' }

$extensions = [regex]::Matches($match.Groups['body'].Value, 'L"(?<ext>\.[^"]+)"') | ForEach-Object { $_.Groups['ext'].Value }
$extensions = @($extensions | Select-Object -Unique)
if ($extensions.Count -lt 1) { throw 'No image extensions were found in image_formats.h.' }

$lines = New-Object System.Collections.Generic.List[string]
$lines.Add('; GENERATED FILE - do not edit directly.')
$lines.Add('; Source of truth: ..\\image_formats.h (GlideFormats::kImageExtensions)')
$lines.Add('; Generated by installer\\generate_associations.ps1 before every installer build.')
foreach ($ext in $extensions) {
    $lines.Add(('Root: HKLM64; Subkey: "Software\\Classes\\Applications\\Glide.exe\\SupportedTypes"; ValueType: string; ValueName: "{0}"; ValueData: ""; Flags: uninsdeletevalue' -f $ext))
    $lines.Add(('Root: HKLM64; Subkey: "Software\\Glide Image Viewer\\Capabilities\\FileAssociations"; ValueType: string; ValueName: "{0}"; ValueData: "Glide.Image"; Flags: uninsdeletevalue' -f $ext))
}

[System.IO.File]::WriteAllLines($OutputPath, $lines, [System.Text.UTF8Encoding]::new($false))
Write-Host ("Generated {0} installer association mappings from image_formats.h." -f $extensions.Count)
